<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" 
	xmlns:llrp="http://www.llrp.org/ltk/schema/core/encoding/binary/1.0"
  xmlns:h="http://www.w3.org/1999/xhtml">
  <!--<xsl:output omit-xml-declaration='yes' method='text' indent='no'/>-->

  <xsl:variable name='prefix'>
    <xsl:value-of select="/llrp:llrpdef/llrp:namespaceDefinition/@prefix"/>
  </xsl:variable>
  <xsl:variable name ="uri">
    <xsl:value-of select="/llrp:llrpdef/llrp:namespaceDefinition/@URI"/>
  </xsl:variable>
  <xsl:variable name ="schemaLocation">
    <xsl:value-of select="/llrp:llrpdef/llrp:namespaceDefinition/@schemaLocation"/>
  </xsl:variable>
  
  <xsl:template name="DefineNameSpaceVariables"  match="/llrp:llrpdef">
    /*
    ***************************************************************************
    *  Copyright 2008 Impinj, Inc.
    *
    *  Licensed under the Apache License, Version 2.0 (the "License");
    *  you may not use this file except in compliance with the License.
    *  You may obtain a copy of the License at
    *
    *      http://www.apache.org/licenses/LICENSE-2.0
    *
    *  Unless required by applicable law or agreed to in writing, software
    *  distributed under the License is distributed on an "AS IS" BASIS,
    *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    *  See the License for the specific language governing permissions and
    *  limitations under the License.
    *
    ***************************************************************************
    */


    /*
    ***************************************************************************
    *
    *  This code is generated by Impinj LLRP .Net generator. Modification is
    *  not recommended.
    *
    ***************************************************************************
    */

    /*
    ***************************************************************************
    * File Name:       LLRPParam.cs
    *
    * Version:         1.0
    * Author:          Impinj
    * Organization:    Impinj
    * Date:            Jan. 18, 2008
    *
    * Description:     This file contains LLRP parameter definitions
    ***************************************************************************
    */

    namespace Org.LLRP.LTK.LLRPV1
    {
    public class LLRPConstants
    {
      public const string NAMESPACE_PREFIX = "<xsl:copy-of select="$prefix"/>";
      public const string NAMESPACE_URI = "<xsl:copy-of select="$uri"/>";
      public const string NAMESPACE_SCHEMALOCATION = "<xsl:copy-of select="$schemaLocation"/>";
    }
    }
  </xsl:template>
</xsl:stylesheet>